### ISSUE TITLE
Haiku versioning

### ISSUE THREAD

**Issue by frranck** [repology/repology-rules#141]
Hello,
It seems the haiku versioning creates inconsistencies, here:
https://repology.org/metapackage/mrboom/versions
The haiku version is turning all other packages to red, when it's actually the same version.
More info:
https://github.com/Javanaise/mrboom-libretro/pull/43

**Comment by frranck** [comment]
@AMDmi3 But  the last release+tag version is 4.5.  Shouldn't the version decided in the developer repo?

**Comment by AMDmi3** [comment]
Sorry, I don't understand the question.

**Comment by frranck** [comment]
I don't asking why a packager can makes all the platforms versions look outdated by picking up a random number, when the last version of the software I released is 4.5.

**Comment by AMDmi3** [comment]
Because there's no way to know the official version, and because you didn't release a new official version soon enough so the packager could use it and not have to reside to a snapshot and invent a fake versioning scheme for it.

**Comment by frranck** [comment]
OK, but is there a reason for not using the releases from github? https://github.com/Javanaise/mrboom-libretro/releases

**Comment by AMDmi3** [comment]
It's planned, but it would only cover a tiny fraction of projects, and would still not be reliable, as it depends on extracting version numbers from unformatted text (e.g. tags or release titles), and extracting github links from packages (may be ambigous, outdated, invalid or missing), so it won't be given any preference.

**Comment by frranck** [comment]
thanks for your fix
